// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"betrack/pkg/api"
	"betrack/pkg/api/handlers"
	"betrack/pkg/config"
	"betrack/pkg/db"
	"betrack/pkg/repositories"
	"betrack/pkg/usecases"
)

// Injectors from wire.go:

func InitializeApi(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	betRepository := repositories.NewBetRepository(gormDB)
	betUseCase := usecases.NewBetUseCase(betRepository)
	betHandler := handlers.NewUserHandler(betUseCase)
	serverHTTP := http.NewServerHTTP(betHandler)
	return serverHTTP, nil
}
